### ISSUE TITLE
[Feature] Enhanced documentation on batch datasets

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#434]
In the [Dataset Terminology](https://power-grid-model.readthedocs.io/en/stable/user_manual/dataset-terminology.html) in the documentation, only a very brief mention is made on what a batch dataset is. There's even less documentation on sparse datasets - not even in the advanced documentation.

For both internal and external core developers, it is a good idea to add some documentation on the sparse datasets.

## TODO

* [x] Extend [dataset terminology](https://power-grid-model.readthedocs.io/en/stable/user_manual/dataset-terminology.html)
  * [x] Batch dataset
    * [x] Sparse batch dataset
    * [x] Dense batch dataset
* [x] Add the [data types](https://github.com/PowerGridModel/power-grid-model/blob/main/src/power_grid_model/data_types.py) file to the [Python API reference](https://power-grid-model.readthedocs.io/en/stable/api_reference/python-api-reference.html)
* [ ] Cross-reference with the [Serialization](https://power-grid-model.readthedocs.io/en/stable/user_manual/serialization.html) documentation
