### ISSUE TITLE
[FEATURE] Power Grid Meta Data components enum

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#613]
## The issue with the current implementation

Currently, all power grid model components are listed only by their strings on the python side. That is bugprone, because typos might go undetected until they end up in production.

Additional problems include:

* string data types do not support type hinting.
* pylint and mypy don't understand the supported string data types
* reviewing may be difficult, both for the user and for the developers

## Proposed solution

* [ ] Runtime creating two `Enum`s from the `power_grid_meta_data` makes sure the enums are always up-to-date. The following code snippet illustrates how that would be possible.
  * [ ] one for the data types
  * [ ] one for the component types
* [ ] Expose in the `__init__.py`
* [ ] Update input data types in all functions where e.g. `data_type` and `component_type` are used
* [ ] Update tests
* [ ] Update docs
* [ ] Update examples
* [ ] Update workshop

```py
>>> from enum import Enum
>>> from power_grid_model import power_grid_meta_data
>>>
>>> power_grid_meta_data.keys()
dict_keys(['input', 'update', 'sym_output', 'asym_output', 'sc_output'])
>>>
>>> PowerGridDataTypes = Enum("PowerGridDataTypes", {data_type: data_type for data_type in power_grid_meta_data}) 
>>>
>>> PowerGridDataTypes
<enum 'PowerGridDataTypes'>
>>> list(PowerGridDataTypes)
[<PowerGridDataTypes.input: 'input'>, <PowerGridDataTypes.update: 'update'>, <PowerGridDataTypes.sym_output: 'sym_output'>, <PowerGridDataTypes.asym_output: 'asym_output'>, <PowerGridDataTypes.sc_output: 'sc_output'>]
>>>
>>> PowerGridComponents = Enum("PowerGridComponents", {component: component for component in power_grid_meta_data[PowerGridDataTypes.input]})
>>> PowerGridComponents
<enum 'PowerGridComponents'>
>>> list(PowerGridComponents)  
[<PowerGridComponents.node: 'node'>, <PowerGridComponents.line: 'line'>, <PowerGridComponents.link: 'link'>, <PowerGridComponents.transformer: 'transformer'>, <PowerGridComponents.three_winding_transformer: 'three_winding_transformer'>, <PowerGridComponents.shunt: 'shunt'>, <PowerGridComponents.source: 'source'>, <PowerGridComponents.sym_gen: 'sym_gen'>, <PowerGridComponents.asym_gen: 'asym_gen'>, <PowerGridComponents.sym_load: 'sym_load'>, <PowerGridComponents.asym_load: 'asym_load'>, <PowerGridComponents.sym_power_sensor: 'sym_power_sensor'>, <PowerGridComponents.asym_power_sensor: 'asym_power_sensor'>, <PowerGridComponents.sym_voltage_sensor: 'sym_voltage_sensor'>, <PowerGridComponents.asym_voltage_sensor: 'asym_voltage_sensor'>, <PowerGridComponents.fault: 'fault'>, <PowerGridComponents.transformer_tap_regulator: 'transformer_tap_regulator'>]
```

**Comment by mgovers** [comment]
Out of scope but keeping here for reference:

## Attributes

Do we also want the component attributes in enums?

* Pros:
  * enums + type hinting all the way
* Con:
  * feels like it will blow up the amount of enums.
  * how do we handle attributes differing per data type?
  * at some point, we might as well start using the code generator instead of power_grid_meta_data

Maybe we can expose it like so:

```py
PowerGridAttributes = {
  component: Enum(
    f"PowerGrid{component.value.title().replace('_', '')}Attributes",
    {attribute: attribute for attribute in power_grid_meta_data[PowerGridDataTypes.input.value][component.value].dtype.names} 
  )                                                                                              
  for component in PowerGridComponents
}
```

or to create class attributes dynamically using something similar to https://stackoverflow.com/questions/1325673/how-to-add-property-to-a-class-dynamically

**Comment by mgovers** [comment]
This is different from #82 because it keeps existing functionality exactly the same - just makes typing easier.

**Comment by figueroa1395** [comment]
## Issue with initially proposed solution

After following the proposed solution and further investigation, I found that dynamically creating data types as Enums is not well understood by linters, defeating the purpose of the feature if implemented this way.

## Update proposed solution
* [ ] Use a code generator (Jinja) to create two `Enum`s, one for the data types and one for the component types,  based on the JSON configuration files.
  * [ ] Make Jinja template for both Enum data types.
  * [ ] Make the python code generator.
* [ ] Expose in the `__init__.py`.
* [ ] Update input data types in all functions where e.g. `data_type` and `component_type` are used.
* [ ] Update tests.
* [ ] Update docs.
* [ ] Update examples.
* [ ] Update workshop.
