### ISSUE TITLE
[FEATURE] make python API core functionality private

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#784]
**Describe the feature request**

Currently, the functionality in `src/power_grid_model/core` is not considered stable. However, it may not be directly clear to the user that that is the case. To show the intentionality, the core module should be marked as a private module by prefixing `_`, i.e., `src/power_grid_model/_core`.

However, because of the intentionality issue, users may not have realized that we do not consider functionality in `core` stable, so as an intermediate step, we should still expose the functions currently listed in `core` in the same way - otherwise, we may break users' workflow, even if it was never intended to be used that way.

## TODO

* [x] move `src/power_grid_model/core` to `src/power_grid_model/_core`
* [x] make a new module `src/power_grid_model/core` that contains the same files as `src/power_grid_model/_core` that import all existing symbols from the `_core` module.
  * [x] this ensures that new functionality is not exposed but existing functionality is not (yet) broken
* [x] ensure all other modules and tests import from `_core` (not from `core`)
