### ISSUE TITLE
[Release] v1.10.0

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#803]
**Before release**

* [x] Everything in `main`
  * [x] Ensure changes that solve #548 are in `main`
    * [x] #771 
    * [x] #793 
    * [x] #801 
  * [x] Ensure documentation changes that solve #797 are in `main`
* [x] Everything in release branch `release/v1.10-rc` in #823 
  * [x] Make branch off `main` in `release/v1.10-rc` in #823
  * [x] Apply changes that solve #784 to this branch (i.e. merge #787 to this branch)
  * [x] Apply changes that solve #774 to this branch (i.e. merge #811 to this branch)
  * [x] Update with `main` if necessary
  * [x] Update [`VERSION`](#VERSION) file
  * [x] Run benchmark RC; compare with `v1.9.0`
* [x] Release
  * [x] Make PR in #823
  * [x] Update with `main` if necessary
  * [x] Merge PR

**After release**

* [x] Update the release notes
  * [x] Add `Highlights` section if needed
  * [x] Any breaking changes: explain + provide migration approach
  * [x] Any deprecations: explain + provide migration approach
* [x] Share with stakeholders
  * [x] Notify maintainers
  * [x] Post to PGM LF Energy mailing list
  * [x] Post to PGM LF Energy Slack channel
  * [x] Post to LinkedIn
  * [x] Share in sprint review

**Comment by mgovers** [comment]
changelog up til [`v1.9.86`](https://github.com/PowerGridModel/power-grid-model/releases/tag/v1.9.86)

## What's Changed
* [Feature] Check generated code by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/658
* Bump fsfe/reuse-action from 3 to 4 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/665
* Bump pypa/cibuildwheel from 2.19.1 to 2.19.2 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/664
* Feature/Added missing metaclass by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/667
* fix #669 transformer tap regulator without other transformer type in data by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/670
* fix also support empty trafo list in validation by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/671
* [BUG] Fix source param calculation by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/672
* Rectify source documentation by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/673
* Drop python 3.9 by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/638
* Feature/main model wrapper by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/660
* [FEATURE] Add simple self_test to Python API by @zhen0427 in https://github.com/PowerGridModel/power-grid-model/pull/674
* Feature/test row based dataset by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/675
* Clearify the reference direction of branch and branch3 by @zhen0427 in https://github.com/PowerGridModel/power-grid-model/pull/679
* Columnar data Python API step 2  by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/676
* [FEATURE] Numerically stable source injection in power flow. by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/666
* Add type hinting in python API by @zhen0427 in https://github.com/PowerGridModel/power-grid-model/pull/680
* Feature/calculation type in options by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/681
* Bump pypa/cibuildwheel from 2.19.2 to 2.20.0 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/683
* Feature / Binary search in Automatic Tap Changer by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/668
* Feature/columnar dataset by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/678
* remove erroneously added unused and test logic after #668 by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/684
* Feature/calculation type options in tests by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/682
* Remove unused alias topology by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/686
* Bugfix/dont crash on invalid homogeneous batch dataset by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/690
* Path changes to cmake files by @Laurynas-Jagutis in https://github.com/PowerGridModel/power-grid-model/pull/689
* Implementation of TypeVar in more scripts by @zhen0427 in https://github.com/PowerGridModel/power-grid-model/pull/685
* Refactor meta data generator to remove lambda hack by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/693
* fix compiler flag with new setuptools by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/694
* Feature/enable mypy for users by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/697
* add columnar data to data types (but don't use yet) by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/663
* license for py.typed by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/701
* Use black-jupyter in pre-commit by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/700
* [BUG] data filter of list to not crash by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/705
* BugFix / Handle access violation to unconnected-regulated transformers by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/703
* Update quickstart.md by @PaulSchulz in https://github.com/PowerGridModel/power-grid-model/pull/709
* Feature/C++ header only wrapper for C API by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/688
* Feature/cpp api tests by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/707
* Refactor data filter functionality by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/704
* Feature/columnar data serialization by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/708
* columnar data python api serialization by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/687
* Allow python 3.13 by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/713
* more efficient columnar deserialization by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/716
* Feature / Add columnar data support in main model  by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/712
* Bump pypa/cibuildwheel from 2.20.0 to 2.21.0 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/721
* Feature / Rename API tests by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/719
* Feature / Columnar data C API by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/711
* fix quick start by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/724
* Renew build guide by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/725
* Bump pypa/cibuildwheel from 2.21.0 to 2.21.1 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/728
* MutableDataset to ConstDataset for columnar data by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/732
* Feature/Update validation for columnar by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/734
* improve user build guide by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/737
* Feature/add nightly by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/736
* Improve C and CPP API target structure by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/741
* remove not-needed handle creation in meta data by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/743
* Feature/nightly part 2 by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/742
* Feature/full clang tidy by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/744
* Update README.md by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/745
* Remove static functions in CPP wrapper by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/747
* add check code quality + citations to nightly by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/750
* Feature / Add enum options to deserialize relevant attributes  by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/746
* Add numpy to mypy check by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/753
* Feature/Update reuse by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/754
* add component attribute filter options to init by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/757
* Feature/columnar dataset python extension by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/699
* remove experimental flag on columnar output by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/759
* Feature / deserialization data filter relevant logic in place by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/758
* Bump pypa/cibuildwheel from 2.21.1 to 2.21.2 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/763
* move datasetype from dataset to _utils by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/761
* Feature/Re route validation tests by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/718
* create generic_branch #729 by @scud-soptim in https://github.com/PowerGridModel/power-grid-model/pull/752
* columnar data batch list conversion  by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/760
* Bug/Fix columnar batch validation function by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/768
* Feature/Add utils to Cpp wrapper by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/767
* Repro case for buffer alignment  by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/769
* Bump actions ubuntu 24.04 by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/770
* Fix Nightly Clang-Tidy run by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/775
* auto tap validation test for meshed grid with transformers by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/777
* Bug/Convert to/form row/col util function by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/779
* Remove sphinx workaround by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/780
* Bump pypa/cibuildwheel from 2.21.2 to 2.21.3 by @dependabot in https://github.com/PowerGridModel/power-grid-model/pull/782
* Add dtype compatibility check by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/776
* Improvement/Integration tests for columnar data by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/778
* [Feature] columnar data Python API docs by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/781
* Bug/Fix feedstock mac by @figueroa1395 in https://github.com/PowerGridModel/power-grid-model/pull/790
* BugFix / Capital enums made lower case by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/792
* Build guide docs - build docs from local by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/789
* Columnar data docs - native data interface serialization by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/788
* Columnar data documentation (Terminology) by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/783
* [Feature] - columnar data examples by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/785
* improve C API documentation by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/799
* Bug / Fix error handling tests in API tests by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/795
* Fix/missing validation of k for generic branch by @scud-soptim in https://github.com/PowerGridModel/power-grid-model/pull/804
* Feature - columnar performance docs by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/801
* Fix const issue in the cpp header by @TonyXiang8787 in https://github.com/PowerGridModel/power-grid-model/pull/808
* BUG in test / Memory access violation in update test by @Jerry-Jinfeng-Guo in https://github.com/PowerGridModel/power-grid-model/pull/810
* Feature/improve docs by @mgovers in https://github.com/PowerGridModel/power-grid-model/pull/807
* Add branch power calculation explanation in docs by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/815
* fix error msg of validator by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/816
* Optional IDs tests by @nitbharambe in https://github.com/PowerGridModel/power-grid-model/pull/817

## New Contributors
* @PaulSchulz made their first contribution in https://github.com/PowerGridModel/power-grid-model/pull/709
* @scud-soptim made their first contribution in https://github.com/PowerGridModel/power-grid-model/pull/752

**Full Changelog**: https://github.com/PowerGridModel/power-grid-model/compare/v1.9.0...v1.9.86

**Comment by TonyXiang8787** [comment]
@mgovers  this should be one of the highlights

https://github.com/PowerGridModel/power-grid-model/pull/666

The source calculation is very important.
